{% set name = "streamlit-aggrid" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d4b776e4e7c2a91808744873843c8236065e263c22cc39e7267383ccc81486a3

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - poetry
    - python
  run:
    - python
    - pandas >=1.2
    - python-decouple >=3.6
    - streamlit >=0.87.0

test:
  imports:
    - st_aggrid
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/PablocFonseca/streamlit-aggrid
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Streamlit component implementation of ag-grid
  description: |
    Streamlit component implementation of ag-grid
  dev_url: https://github.com/PablocFonseca/streamlit-aggrid
  doc_url: https://streamlit-aggrid.readthedocs.io

extra:
  recipe-maintainers:
    - maxibor
    - timkpaine
  skip-lints:
    - missing_wheel
